config/routes.rb
Fuzzybear::Application.routes.draw do

  root   'home#index'

  get    "/home/index"             => 'home#index',             as: 'home_index'
  get    '/home'                   => 'home#index',             as: 'home'

  get    '/register'               => 'sessions#register_page', as: 'register'
  post   '/sessions'               => 'sessions#create',        as: 'sessions_path'
  get    '/session-expired-notice' => 'sessions#expired_notice'

  get    '/login/'                 => 'sessions#login_page',    as: 'login'
  delete '/logout/'                => 'sessions#destroy',       as: 'logout'

  get    '/forgot-password'        => 'password_reset#new',              as: 'new_password_reset' # Serve form to request pw change token
  post   '/forgot-password'        => 'password_reset#create',           as: 'create_password_reset' # Submitted a form to request new token
  get    '/set-new-password'       => 'password_reset#set_new_password', as: 'set_new_password' # Serve form to change password
  post   '/change_password'        => 'password_reset#change_password',  as: 'change_password' # Submit new password and confirmation

  get    '/store/'                 => 'store#index',                     as: 'store_index'
  get    '/store/search'           => 'store#product_search',            as: 'store_search'

  get    '/cart/'                  => 'cart#index',                      as: 'cart_index'
  get    '/cart/is-empty'          => 'cart#is_empty',                   as: 'cart_is_empty'
  put    '/cart/'                  => 'cart#update',                     as: 'cart_update'
  delete '/cart/'                  => 'cart#destroy',                    as: 'clear_cart'

  get  '/checkout/'                => 'checkout#index'
  post '/checkout/submit'          => 'orders#create'

  post   '/user-customer'                    => 'user_customer#create',  as: 'create_my_account'
  get    '/user-customer/:id(.:format)/edit' => 'user_customer#edit',    as: 'edit_my_account'
  patch  '/user-customer/:id(.:format)'      => 'user_customer#update',  as: 'update_my_account'
  delete '/user-customer/:id'                => 'user_customer#destroy', as: 'delete_my_account'

  post   '/user-customer-address'               => 'user_customer_address#create',  as: 'create_address'
  get    '/user-customer-address/:id(.:format)' => 'user_customer_address#edit',    as: 'edit_my_addresses'
  patch  '/user-customer-address/:id(.:format)' => 'user_customer_address#update',  as: 'update_my_address'
  delete '/user-customer-address/:id'           => 'user_customer_address#destroy', as: 'delete_address'

  get  '/customer/:id/orders'                   => 'orders#index',    as: 'customer_orders'
  get  '/customer/:id/order/:id'                => 'orders#show',     as: 'customer_order'

  get    '/staff-edit-customer'               => 'staff_edit_customer#index',   as: 'staff_edit_customers'
  get    '/staff-edit-customer/:id(.:format)' => 'staff_edit_customer#edit',    as: 'staff_edit_customer'
  patch  '/staff-edit-customer/:id(.:format)' => 'staff_edit_customer#update',  as: 'staff_update_customer'
  delete '/staff-edit-customer/:id'           => 'staff_edit_customer#destroy', as: 'staff_delete_customer'

  post   '/staff-edit-customer-address'               => 'staff_edit_customer_address#create',  as: 'staff_create_customer_address'
  get    '/staff-edit-customer-address/:id(.:format)' => 'staff_edit_customer_address#edit',    as: 'staff_edit_customer_addresses'
  patch  '/staff-edit-customer-address/:id(.:format)' => 'staff_edit_customer_address#update',  as: 'staff_update_customer_address'
  delete '/staff-edit-customer-address/:id'           => 'staff_edit_customer_address#destroy', as: 'staff_delete_customer_address'

  post   '/admin-edit-staff'               => 'admin_edit_staff#create',  as: 'create_staff'
  get    '/admin-edit-staff'               => 'admin_edit_staff#index',   as: 'staff_index'
  get    '/admin-edit-staff/:id(.:format)' => 'admin_edit_staff#edit',    as: 'edit_staff'
  patch  '/admin-edit-staff/:id(.:format)' => 'admin_edit_staff#update',  as: 'update_staff'
  delete '/admin-edit-staff/:id'           => 'admin_edit_staff#destroy', as: 'delete_staff'

end

app/views/user_addresses/edit.html.erb
<a href="#formTop"></a>
<div class="row">
  <div class="col-xs-12">
    
    <%= render "/partials/flash_message" %>

    <%= form_for @user do |f| %>

      <%= hidden_field_tag :current_tab, controller_name %>

      <div class="panel panel-default">

        <div class="panel-body">
          <div class="row">

            <%= render partial: "users/navtabs", locals: {user: @user} %>

            <!-- Tab panes -->
            <div class="tab-content">

              <!-- My Addresses -->
              <div class="tab-pane active" id="myAddresses">
                <div class="col-xs-12">

                  <div class="well" style="margin-top: 20px;">
                    You currently have <%= @user.addresses.where(deleted: false).count %> addresses.

                    <%= link_to user_create_address_path(@user), method: :post do %>
                      <button id="createAddress" type="button" class="btn btn-default">Add Another Address</button>
                    <% end %>
                  </div>

                  <div class="row">
                    <% @user.addresses.order(:id).each do |address| %>
                      <%= f.fields_for :addresses, address do |address_form| %>
                        <% if address.deleted == false %>
                          <%= render "users/partials/user_address", {
                            f: address_form,
                            address: address,
                            userForm: f,
                            user: @user
                          } %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>

                </div>
              </div>

            </div>
          </div>
        </div>
      </div>

      <div style="height: 66px;">
        <div class="panel-body">
          <div class="panel" style="border: none;">
            <button id="submitButton" type="submit" class="btn btn-primary pull-right">Update Details</button>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div>