config/routes.rb
Fuzzybear::Application.routes.draw do

  root   'home#index'

  get    "/home/index"             => 'home#index',             as: 'home_index'
  get    '/home'                   => 'home#index',             as: 'home'

  get    '/register'               => 'sessions#register_page', as: 'register'
  post   '/sessions'               => 'sessions#create',        as: 'sessions_path'
  get    '/session-expired-notice' => 'sessions#expired_notice'

  get    '/login/'                 => 'sessions#login_page',    as: 'login'
  delete '/logout/'                => 'sessions#destroy',       as: 'logout'

  get    '/forgot-password'        => 'password_reset#new',              as: 'new_password_reset' # Serve form to request pw change token
  post   '/forgot-password'        => 'password_reset#create',           as: 'create_password_reset' # Submitted a form to request new token
  get    '/set-new-password'       => 'password_reset#set_new_password', as: 'set_new_password' # Serve form to change password
  post   '/change_password'        => 'password_reset#change_password',  as: 'change_password' # Submit new password and confirmation

  get    '/store/'                 => 'store#index',                     as: 'store_index'
  get    '/store/search'           => 'store#product_search',            as: 'store_search'

  get    '/cart/'                  => 'cart#index',                      as: 'cart_index'
  get    '/cart/is-empty'          => 'cart#is_empty',                   as: 'cart_is_empty'
  put    '/cart/'                  => 'cart#update',                     as: 'cart_update'
  delete '/cart/'                  => 'cart#destroy',                    as: 'clear_cart'

  get  '/checkout/'                => 'checkout#index'
  post '/checkout/submit'          => 'orders#create'

  post   '/user-customer'                    => 'user_customer#create',  as: 'create_my_account'
  get    '/user-customer/:id(.:format)/edit' => 'user_customer#edit',    as: 'edit_my_account'
  patch  '/user-customer/:id(.:format)'      => 'user_customer#update',  as: 'update_my_account'
  delete '/user-customer/:id'                => 'user_customer#destroy', as: 'delete_my_account'

  post   '/user-customer-address'               => 'user_customer_address#create',  as: 'create_address'
  get    '/user-customer-address/:id(.:format)' => 'user_customer_address#edit',    as: 'edit_my_addresses'
  patch  '/user-customer-address/:id(.:format)' => 'user_customer_address#update',  as: 'update_my_address'
  delete '/user-customer-address/:id'           => 'user_customer_address#destroy', as: 'delete_address'

  get  '/customer/:id/orders'                   => 'orders#index',    as: 'customer_orders'
  get  '/customer/:id/order/:id'                => 'orders#show',     as: 'customer_order'

  get    '/staff-edit-customer'               => 'staff_edit_customer#index',   as: 'staff_edit_customers'
  get    '/staff-edit-customer/:id(.:format)' => 'staff_edit_customer#edit',    as: 'staff_edit_customer'
  patch  '/staff-edit-customer/:id(.:format)' => 'staff_edit_customer#update',  as: 'staff_update_customer'
  delete '/staff-edit-customer/:id'           => 'staff_edit_customer#destroy', as: 'staff_delete_customer'

  post   '/staff-edit-customer-address'               => 'staff_edit_customer_address#create',  as: 'staff_create_customer_address'
  get    '/staff-edit-customer-address/:id(.:format)' => 'staff_edit_customer_address#edit',    as: 'staff_edit_customer_addresses'
  patch  '/staff-edit-customer-address/:id(.:format)' => 'staff_edit_customer_address#update',  as: 'staff_update_customer_address'
  delete '/staff-edit-customer-address/:id'           => 'staff_edit_customer_address#destroy', as: 'staff_delete_customer_address'

  post   '/admin-edit-staff'               => 'admin_edit_staff#create',  as: 'create_staff'
  get    '/admin-edit-staff'               => 'admin_edit_staff#index',   as: 'staff_index'
  get    '/admin-edit-staff/:id(.:format)' => 'admin_edit_staff#edit',    as: 'edit_staff'
  patch  '/admin-edit-staff/:id(.:format)' => 'admin_edit_staff#update',  as: 'update_staff'
  delete '/admin-edit-staff/:id'           => 'admin_edit_staff#destroy', as: 'delete_staff'

end

app/controllers/user_customer_controller.rb
class UserCustomerController < UserCustomerBaseController

  # User who is a customer.
  # This controller allows customers to edit their own details

  before_action :require_logged_in, except: [:create]

  # A new customer wants to create an account.
  # Recive form submission for the create.
  def create
    @customer = User.new(sane_user_params)
    if @customer.save
      puts "-----> Created Account successfully!!!"
      flash[:just_signed_up] = true;
      session[:current_user_id] = @customer.id
      render :json => @customer, :status => 201 # created
    else
      puts "-----> Failed to Create Account!!!"
      render :json => @customer.errors, :status => 400 # bad request
    end
  end

  # Customer wants to edit the basic details of his own account
  # Serve the edit form.
  def edit
    render locals: {
      user: User.find(params[:id])
    }
  end

  # Customer wants to update the basic details of his own account
  # Recive form submission for the update.
  def update
    @customer = User.find(params[:id])
    @customer.update_attributes!(sane_user_params)
    flash[:success] = "Successfully updated your details"
    logger.debug "Updated customer. params[:current_tab]: #{params[:current_tab]}"
    redirect_to edit_my_account_path(@customer)
  end

  # Customer wants to delete his own account.
  def destroy
    @customer = User.find_by(id: params[:id])
    if @customer.nil?
      flash[:notice] = "Customer #{params[:id]} not found."
      #redirect_to manage_customers_path
    else
      if @customer.addresses.count > 0
        @customer.addresses.each do |address|
          address.destroy
        end
      end
      deletedCustomer = "#{@customer.id} (Name: #{@customer.first_name} #{@customer.last_name}, Email: #{@customer.email})."
      @customer.destroy
      flash[:success] = "Successfully deleted your account. #{deletedCustomer}"
      #redirect_to manage_customers_path
    end
  end
end

app/views/user_customer/_navtabs.html.erb
<!-- Tab header -->
<div class="col-xs-12" style="height:30px;"><b>Editing <%= controller_name.singularize %>:</b> <span class="feint"><%= user.first_name %>&nbsp<%= user.last_name %></span>
</div>

<ul class="nav nav-tabs" role="tablist" id="accountDetailTabs">

  controller_name: <%= controller_name %> </br>
  action: <%= params[:action] %></br>

  <% if controller_name == "user_customer" || controller_name == "user_customer_address" %>
    <%= navtab_li 'user_customer/edit' %>
      <%= link_to edit_my_account_path(user) do %> Details <% end %>
    </li>
    <%= navtab_li 'user_customer_address/edit' %>
      <%= link_to edit_my_addresses_path(user) do %> Shipping / Billing Addresses <% end %>
    </li>
  <% end %>
  
</ul>

app/views/user_customer/edit.html.erb
<div>USER CUSTOMER</div>

<%= form_for user, url: {:controller => "user_customer", :action => "update"} do |f| %>


<a href="#formTop"></a>

<div class="row">

  <div class="col-xs-12">
    
    <%= render "/partials/flash_message" %>

    <%= render "/user_partials/just_signed_up", {user: user} %>

    <%= hidden_field_tag :current_tab, controller_name %>

    <div class="panel panel-default">

      <div class="panel-body">

        <div class="row">

          <%= render partial: "/user_customer/navtabs", locals: {user: user} %>

          <!-- Tab panes -->
          <div class="tab-content">

            <!-- Account Details -->
            <div class="tab-pane active" id="accountDetails">

              <div class="col-xs-12">

                <%= render '/user_customer/partials/usertype', { user: user, f: f } %>

                <%= render '/user_partials/edit_basic_details', { user: user, f: f } %>

                <div class="form-group">
                  <button id="submitButton" type="submit" class="btn btn-primary pull-right">Update Details</button>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>