config/routes.rb
Fuzzybear::Application.routes.draw do

  root   'home#index'

  get    "/home/index"             => 'home#index',             as: 'home_index'
  get    '/home'                   => 'home#index',             as: 'home'

  get    '/register'               => 'sessions#register_page', as: 'register'
  post   '/sessions'               => 'sessions#create',        as: 'sessions_path'
  get    '/session-expired-notice' => 'sessions#expired_notice'

  get    '/login/'                 => 'sessions#login_page',    as: 'login'
  delete '/logout/'                => 'sessions#destroy',       as: 'logout'

  get    '/forgot-password'        => 'password_reset#new',              as: 'new_password_reset' # Serve form to request pw change token
  post   '/forgot-password'        => 'password_reset#create',           as: 'create_password_reset' # Submitted a form to request new token
  get    '/set-new-password'       => 'password_reset#set_new_password', as: 'set_new_password' # Serve form to change password
  post   '/change_password'        => 'password_reset#change_password',  as: 'change_password' # Submit new password and confirmation

  get    '/store/'                 => 'store#index',                     as: 'store_index'
  get    '/store/search'           => 'store#product_search',            as: 'store_search'

  get    '/cart/'                  => 'cart#index',                      as: 'cart_index'
  get    '/cart/is-empty'          => 'cart#is_empty',                   as: 'cart_is_empty'
  put    '/cart/'                  => 'cart#update',                     as: 'cart_update'
  delete '/cart/'                  => 'cart#destroy',                    as: 'clear_cart'

  get  '/checkout/'                => 'checkout#index'
  post '/checkout/submit'          => 'orders#create'

  post   '/user-customer'                    => 'user_customer#create',  as: 'create_my_account'
  get    '/user-customer/:id(.:format)/edit' => 'user_customer#edit',    as: 'edit_my_account'
  patch  '/user-customer/:id(.:format)'      => 'user_customer#update',  as: 'update_my_account'
  delete '/user-customer/:id'                => 'user_customer#destroy', as: 'delete_my_account'

  post   '/user-customer-address'               => 'user_customer_address#create',  as: 'create_address'
  get    '/user-customer-address/:id(.:format)' => 'user_customer_address#edit',    as: 'edit_my_addresses'
  patch  '/user-customer-address/:id(.:format)' => 'user_customer_address#update',  as: 'update_my_address'
  delete '/user-customer-address/:id'           => 'user_customer_address#destroy', as: 'delete_address'

  get  '/customer/:id/orders'                   => 'orders#index',    as: 'customer_orders'
  get  '/customer/:id/order/:id'                => 'orders#show',     as: 'customer_order'

  get    '/staff-edit-customer'               => 'staff_edit_customer#index',   as: 'staff_edit_customers'
  get    '/staff-edit-customer/:id(.:format)' => 'staff_edit_customer#edit',    as: 'staff_edit_customer'
  patch  '/staff-edit-customer/:id(.:format)' => 'staff_edit_customer#update',  as: 'staff_update_customer'
  delete '/staff-edit-customer/:id'           => 'staff_edit_customer#destroy', as: 'staff_delete_customer'

  post   '/staff-edit-customer-address'               => 'staff_edit_customer_address#create',  as: 'staff_create_customer_address'
  get    '/staff-edit-customer-address/:id(.:format)' => 'staff_edit_customer_address#edit',    as: 'staff_edit_customer_addresses'
  patch  '/staff-edit-customer-address/:id(.:format)' => 'staff_edit_customer_address#update',  as: 'staff_update_customer_address'
  delete '/staff-edit-customer-address/:id'           => 'staff_edit_customer_address#destroy', as: 'staff_delete_customer_address'

  post   '/admin-edit-staff'               => 'admin_edit_staff#create',  as: 'create_staff'
  get    '/admin-edit-staff'               => 'admin_edit_staff#index',   as: 'staff_index'
  get    '/admin-edit-staff/:id(.:format)' => 'admin_edit_staff#edit',    as: 'edit_staff'
  patch  '/admin-edit-staff/:id(.:format)' => 'admin_edit_staff#update',  as: 'update_staff'
  delete '/admin-edit-staff/:id'           => 'admin_edit_staff#destroy', as: 'delete_staff'

end

app/controllers/staff_edit_customer_controller.rb
class StaffEditCustomerController < StaffEditCustomerBaseController

  # This controller allows staff to edit customer details.

  # Staff wants to view a list of existing customers.
  def index
    @customers = User.where(usertype: "customer").
                      where.not(id: current_user.id).order(:email)
  end

  # Staff wants to edit the basic details of an existing customer.
  # Serve the edit form.
  def edit
    @customer = User.find(params[:id])
  end

  # Staff wants to update the basic details of an existing customer.
  # Recive form submission for the update.
  def update
    @customer = User.find(params[:id])
    @customer.update_attributes!(sane_user_params)
    flash[:success] = "Successfully updated customer details"
    logger.debug "Updated customer. params[:current_tab]: #{params[:current_tab]}"
    #redirect_to edit_customer_path(@customer)
  end

  # Staff wants to delete an existing customer.
  def destroy
    puts "DELETE CUSTOMER #{params[:id]}"
    @customer = User.find_by(id: params[:id])
    if @customer.nil?
      flash[:notice] = "Customer #{params[:id]} not found."
      #redirect_to manage_customers_path
    else
      if @customer.addresses.count > 0
        @customer.addresses.each do |address|
          address.destroy
        end
      end
      deletedCustomer = "#{@customer.id} (Name: #{@customer.first_name} #{@customer.last_name}, Email: #{@customer.email})."
      @customer.destroy
      flash[:success] = "Deleted Customer #{deletedCustomer}"
      puts "redirecting to customer list..."
      redirect_to staff_edit_customers_path
    end
  end
end

app/views/staff_edit_customer/partials/_customer_list.html.erb
<div class="col-xs-12">
  <div class="well manage-users-page customerwell tiny-font">

    <div class="row">
      <div class="col-xs-10">
        <%= render "/staff_edit_customer/partials/list_basic", {user:user} %>
        <hr>
        <div class="row">
          <div class="col-xs-12">
            <span class="feint datahead">User Type: </span>
            <span class="datarow"><%= user.usertype %></span>
          </div>
        </div>
      </div>
      <div class="col-xs-2">
        <%= link_to staff_delete_customer_path(user), method: :delete, class: 'user-delete pull-right', style:"text-decoration:none;" do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <%= link_to staff_edit_customer_path(user), class: 'pull-right' do %>
          <button id=<%="editUser#{user.id}"%> type="button" class="btn btn-default">Edit User</button>
        <% end %>
      </div>
    </div>
    
  </div>
</div>

app/views/staff_edit_customer/partials/_list_basic.html.erb
<div class="row">
  <div class="col-xs-11">
    <span class="feint datahead">Name: </span>
    <span class="datarow">
      <%= user.first_name %>
      <%= user.last_name %>
    </span>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <span class="feint datahead">Email: </span>
    <span class="datarow"><%= user.email %></span>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <span class="feint datahead">Home Ph: </span>
    <span class="datarow"><%= user.home_phone %></span>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <span class="feint datahead">Work Ph: </span>
    <span class="datarow"><%= user.work_phone %></span>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <span class="feint datahead">Mobile Ph: </span>
    <span class="datarow"><%= user.mobile_phone %></span>
  </div>
</div>